### PR TITLE
[test] Update now.json

### PR DESCRIPTION
**Pull request by arunoda**

### CODE REVIEW

**Comment by arunoda** [comment]
Closing as ZEIT integration works here.
(I work at ZEIT)

**Comment by Ailrun** [comment]
@arunoda I already checked it works when I changed this repo to public one. It didn't work when this repo is private.

**Comment by Ailrun** [comment]
See #3 and #4

**Comment by Ailrun** [comment]
(Though start point of #1 is removed since when I make this repo public I removed my forked repo and reforked the repo again)

**Pull request closed without merging**
